import React from 'react';
import './App.css';
import { Route, Routes } from 'react-router-dom';
import PlacePage from './pages/place-page/place-page';
import DashboardBaseLayout from './layouts/dashboard-base-layout/dashboard-base-layout';
import LibrariesPage from './pages/libraries-page/libraries-page';
import CaffeDetailPage from './pages/caffe-detail-page/caffe-detail-page';
import CaffesPage from './pages/caffes-page/caffes-page';
import LibraryDetailPage from './pages/library-detail-page/library-detail-page';
import BanksPage from './pages/banks-page/banks-page';
import BankDetailPage from './pages/bank-detail-page/bank-detail-page';
import HomePage from './pages/home-page/home-page';
import InBaseLayout from './layouts/in-base-layout/in-base-layout';
import Home23 from './pages/home--/home';

function App() {

  const banks = [
    { id: 1, name: 'Akbank', branch: 'Akbank Başakşehir Şubesi', capacity: 48, city: 'İstanbul', country: 'Başakşehir', address: 'Ziya Gökalp, TÜMSAN 1. Kısım Sanayi Sitesi No:23, 34490 İkitelli Osb/Başakşehir/İstanbul', logo: 'https://www.akbank.com/SiteAssets/img/akbfa.jpg', images: 'https://fastly.4sqi.net/img/general/600x600/63268521_UTe0ul5oCsbTBDnmD4L1vNXwChCNe3NU0MaYt0pErrE.jpg' },
    { id: 2, name: 'Vakıfbank', branch: 'Vakıfbank Beşiktaş Şubesi', capacity: 45, city: 'İstanbul', country: 'Beşiktaş', address: 'Cihannüma, Barbaros Blv. No:89A, 34353 Beşiktaş/İstanbul', logo: 'https://www.vakifbank.com.tr/images/vakifbank.logo.jpg', images: 'https://lh3.googleusercontent.com/p/AF1QipMONVfnZsamEYT0DIXB3umOseavSgvWaoGEJ8gq=s680-w680-h510' },
    { id: 3, name: 'Vakıfbank', branch: 'Vakıfbank Kadıköy Şubesi', capacity: 45, city: 'İstanbul', country: 'Kadıköy', address: 'Osmanağa, Söğütlü Çeşme Cd No:5, 34714 Kadıköy/İstanbul', logo: 'https://www.vakifbank.com.tr/images/vakifbank.logo.jpg', images: 'https://lh3.googleusercontent.com/p/AF1QipP344i2CG9sbRmzWNei9nmzowj8EkHktbqVqNsS=s680-w680-h510' },
    { id: 4, name: 'Vakıfbank', branch: 'Vakıfbank Çevik Kuvvet Şubesi', capacity: 35, city: 'İstanbul', country: 'Bayrampaşa', address: 'Ortamahalle Mah. Abdi İpekçi Cad. No:3-5 Bayrampaşa/İstanbul', logo: 'https://www.vakifbank.com.tr/images/vakifbank.logo.jpg', images: 'https://haritane.com/yer/vakifbank-bayrampasa-subesi-553473.jpg' },
    { id: 5, name: 'Ziraatbank', branch: 'Ziraat Bankası İstanbul Mecidiyeköy Şubesi', capacity: 52, city: 'İstanbul', country: 'Şişli', address: 'Merkez, Büyükdere Cd. No:83, 34381 Şişli/İstanbul', logo: 'https://www.ziraatbank.com.tr/PublishingImages/Subpage/bankamiz/BankamizGorselleri/zb_logo.jpg', images: 'https://lh3.googleusercontent.com/p/AF1QipOF_LUIKx5QM55d3sQ8kQwBZGiN0s3DNxdQNTVl=s680-w680-h510' },
    { id: 6, name: 'Kuveyt Türk', branch: 'Kuveyt Türk Avcılar Şubesi', capacity: 43, city: 'İstanbul', country: 'Avcılar', address: 'Reşitpaşa Cad. Yazgan Apartmanı A Blok No:39/1 Avcilar / Istanbul', logo: 'https://katilimfinans.com.tr/images/haberler/2023/12/kuveyt_turk_tuzel_musterilerin_ihale_sureclerini_kolaylastiran_bankpro_ile_is_birligi_yapti_h14455_f6d87.jpg', images: 'https://avatars.mds.yandex.net/get-altay/2004078/2a00000170188296fde07a980acdf6235704/orig' },
    { id: 7, name: 'Yapı Kredi', branch: 'Yapı Kredi - Fatih Akdeniz Caddesi Şubesi', capacity: 47, city: 'İstanbul', country: 'Fatih', address: 'Akşemsettin, Mah. No: /A, Akdeniz Cd. No:99, 34080 Fatih', logo: 'https://www.otostil.com/wp-content/uploads/2017/07/Yap%C4%B1-kredi-bank-logo.jpg', images: 'https://avatars.mds.yandex.net/get-altay/1546239/2a0000016b31d564e189d28d1fbef4e8dcc4/L_height' },
    { id: 8, name: 'DenizBank', branch: 'DenizBank Silivri Şubesi', capacity: 52, city: 'İstanbul', country: 'Silivri', address: 'DenizBank Silivri branchsi', logo: 'https://sbmguvenlik.com.tr/wp-content/uploads/2020/11/denizbank-logo.png', images: 'https://ozkankac.files.wordpress.com/2011/05/denizbankcivril.jpg' },
    { id: 9, name: 'İş Bankası', branch: 'Türkiye İş Bankası Zeytinburnu/İstanbul Şubesi', capacity: 48, city: 'İstanbul', country: 'Zeytinburnu', address: 'Nuripaşa, Merv Cd. No:46A, 34025 Zeytinburnu/İstanbul', logo: 'https://logowik.com/content/uploads/images/turkiye-is-bankasi9178.jpg', images: 'https://static-pano.maps.yandex.ru/v1/?panoid=1246204497_806657233_23_1412759032&size=500%2C240&azimuth=-1.4&tilt=10&api_key=maps&signature=2k1V6u4qz9nb6QWrGpua_c6qCG3y8SGeE5k7qM3bbnU=' },
    { id: 10, name: 'Halkbank', branch: 'Halkbank Üsküdar Şubesi', capacity: 39, city: 'İstanbul', country: 'Üsküdar', address: 'Ahmediye Mah, Halk Cd. No: 7, 34672 Üsküdar/İstanbul', logo: 'https://www.halkbank.com.tr/content/dam/halkbank/tr/gorseller/bankam%C4%B1z/logolarimiz/hblogoerkek.jpg', images: 'https://static.daktilo.com/sites/1192/uploads/2023/04/14/halkb.png' },
    { id: 11, name: 'Garanti BBVA', branch: 'Garanti BBVA Beykoz Şubesi', capacity: 55, city: 'İstanbul', country: 'Beykoz', address: 'Merkez, Kelle İbrahim Cd. No: 2, 34820 Beykoz/İstanbul', logo: 'https://cdnuploads.aa.com.tr/uploads/sirkethaberleri/Contents/2018/11/30/thumbs_b_c_eee85060d5e32db6d1bb1e2da1ca285e.jpg', images: 'https://static-pano.maps.yandex.ru/v1/?panoid=1247327735_805902217_23_1415449747&size=500%2C240&azimuth=-119.8&tilt=10&api_key=maps&signature=lXphMrcwESI8EN-bjpHbGqSQO6dEEtcyf4Sot2nUgRE=' },
    { id: 12, name: 'Şekerbank', branch: 'Şekerbank Kadıköy Şubesi', capacity: 49, city: 'İstanbul', country: 'Kadıköy', address: 'Osmanağa mah. Efes iş hanı, Kuşdili Cd. 12/A, Kadıköy/İstanbul', logo: 'https://www.logovector.org/wp-content/uploads/logos/png/s/sekerbank_logo.png', images: 'https://avatars.mds.yandex.net/get-altay/467304/2a0000015c0131bccd127cb6d962e13676d7/orig' }
  ];

  const libraries = [
    { id: 13, name: 'Merkezefendi Kütüphanesi', capacity: 125, address: 'Merkezefendi, Dere Sk. No:7, 34015 Zeytinburnu/İstanbul', images: ['https://kulturvadisi.com/images/media/zeytinburnu_kultur_vadisi_merkezefendi_2.jpg', 'https://cdnuploads.aa.com.tr/uploads/PhotoGallery/2018/06/17/thumbs_b2_59df3cfd5c8735f91b62b2081473aeed.jpg'] },
    { id: 14, name: 'Başakşehir Millet Kıraathanesi', capacity: 144, address: 'Kayabaşı, Adnan Menderes Bulvari, 34494 Başakşehir/İstanbul', images: ['https://articephe.com/wp-content/uploads/2016/06/SKYLIGHT-1920x960.jpg', 'https://www.basaksehir.bel.tr/Content/images/projeler/proje-galerileri/Bakmer/Millet%20k%C4%B1raathanesi/millet%20k%C4%B1rathanesi%203.png'] },
    { id: 15, name: 'Avcılar İlçe Halk Kütüphanesi', capacity: 92, address: 'Merkez Reşit Paşa Cad. Barış Manço Kültür Merkezi, 34310 Avcılar/İstanbul', images: ['https://images.gonulluyuzbiz.gov.tr/public/165.jpg?width=520&height=370&mode=crop', 'https://cicicee.com/wp-content/uploads/2013/04/avcilar-baris-manco-kultur-merkezi-1000x600.jpg'] },
    { id: 16, name: 'Beyazıt Devlet Kütüphanesi', capacity: 128, address: 'Beyazıt, Çadırcılar Cd. No:34126, 34126 Fatih/İstanbul', images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Beyaz%C4%B1t_Library.jpg/800px-Beyaz%C4%B1t_Library.jpg', 'https://arkitektuel.com/wp-content/uploads/2017/02/beyazit8-640x427.jpg'] },
    { id: 17, name: 'Büyükçekmece Mimar Sinan Halk Kütüphanesi', capacity: 112, address: 'Dızdarıye, Yurt Sk. No:6, 34500 Büyükçekmece/İstanbul', images: ['https://istanbul.ktb.gov.tr/Resim/348090,ktpbuyukcekmece-mimar-sinan-halk-kutuphanesipng.png?0', ''] },
    { id: 18, name: 'Gaziosmanpaşa İlçe Halk Kütüphanesi', capacity: 102, address: 'Merkez, Kültür Sanat Merkezi, 1, Cumhuriyet Meydanı Kat:1, 34245 Gaziosmanpaşa/İstanbul', images: ['https://istanbul.ktb.gov.tr/Resim/348404,ktpgaziosmanpasa-ilce-halk-kutuphanesijpg.png?0', ''] },
    { id: 19, name: 'İstanbul Havalimanı Kütüphanesi', capacity: 98, address: 'Taşoluk, AIRPORT TRANSFER COMPANY, Terminal Caddesi No:1, 34283 Arnavutköy/İstanbul', images: ['https://www.istairport.com/media/xsjfiqlz/kutuphane.jpg?format=webp', 'https://www.basyaybir.org/SFolder/Haber/7592_R1_B3.jpg'] },
    { id: 20, name: 'İstanbul Akyakapark AVM Kütüphanesi', capacity: 115, address: 'kütüphane, Saray, Küçüksu Cd. No: 7, 34768 Ümraniye/İstanbul Akyaka avm, D:2.kat, 34768 Ümraniye/İstanbul', images: ['https://cdnuploads.aa.com.tr/uploads/VideoGallery/2021/03/31/a2433a11587155ae1915e0852f2b50fa.jpg', 'https://cdnuploads.aa.com.tr/uploads/Contents/2020/11/21/thumbs_b_c_5b10be161e34c070c732cfc53d2dfaf3.jpg?v=155615'] },
    { id: 21, name: 'Akm Sanat Kütüphanesi', capacity: 88, address: 'Gümüşsuyu, AKM, Mete Cd. No: 2, 34437 Beyoğlu/İstanbul', images: ['https://www.tuketicipostasi.com/images/haberler/2021/10/vitali-hakko-kreatif-endustriler-kutuphanesi-akm-de.jpg', 'https://img.piri.net/mnresize/600/-/resim/imagecrop/2021/11/12/07/25/resized_e91c3-837ce3c71635538894_vitali_hakko_kreatif_endustriler_kutuphanesi__2_.jpg'] },
    { id: 22, name: 'Üsküdar Şemsipaşa İlçe Halk Kütüphanesi', capacity: 102, address: 'Mimar Sinan, Harem Yolu No:6, 34664 Üsküdar/İstanbul', images: ['https://workindoor.com/dimg/istanbul/uskudar/semsipasa-ilce-halk-kutuphanesi/247403091723699234051351672952_SAM_1653.JPG.jpeg', 'https://i.ytimg.com/vi/xjxGzBWaIOo/maxresdefault.jpg'] },
  ];

  const caffes = [
    { id: 23, name: 'Kahve Dünyası', capacity: 125, branch: 'Akaretler', city: 'İstanbul', country: 'Beşiktaş', address: 'Vişnezade, Şair Nedim Cd. No:13 D:15, 34357 Beşiktaş/İstanbul', logo: 'https://logowik.com/content/uploads/images/626_kahvedunyasi.jpg', images: ['https://live.staticflickr.com/5275/6935215630_e3d223b4b8_b.jpg', 'https://s3-media0.fl.yelpcdn.com/bphoto/qKXSJUFLVYzWtEcrFOqyxQ/348s.jpg'] },
    { id: 24, name: 'Kahve Dünyası', capacity: 70, branch: 'Maslak', city: 'İstanbul', country: 'Sarıyer', address: 'Windowist Tower Reşitpaşa Mah. Eski Büyükdere Cad. No:26/2', logo: 'https://logowik.com/content/uploads/images/626_kahvedunyasi.jpg', images: ['https://www.pausedergi.com/wp-content/uploads/2019/11/1574061071_Kahve_D__nyas___Levent_Alg__t__r__6_.jpg', 'https://foodinlife.com/wp-content/uploads/2022/12/Adsiz-tasarim-24-1.png'] },
    { id: 25, name: 'Kahve Dünyası', capacity: 68, branch: 'Kabataş', city: 'İstanbul', country: 'Beşiktaş', address: 'Levent Mah. Büyükdere Cad. No:146', logo: 'https://logowik.com/content/uploads/images/626_kahvedunyasi.jpg', images: ['https://ayhanmuhendislik.com.tr/wp-content/uploads/2021/09/kabatas-kahve-dunyasi-3.jpeg', 'https://media-cdn.tripadvisor.com/media/photo-s/17/77/47/0f/photo0jpg.jpg'] },
    { id: 26, name: 'Kahve Dünyası', capacity: 92, branch: 'Galataport', city: 'İstanbul', country: 'Beyoğlu', address: 'Kılıçali Paşa, Meclis-i Mebusan Cd. No:10, 34425 Beyoğlu/İstanbul', logo: 'https://logowik.com/content/uploads/images/626_kahvedunyasi.jpg', images: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSw4fLRqxpT0KPlHkr1jCIwpqRonbN31mTeZJMeSvEXvVwqJJBKgqRMARcrx_XxV8bhXK4&usqp=CAU', 'https://mudavim.net/wp-content/uploads/2021/11/kahve-dunyasi-galataport-1-scaled.jpeg'] },
    { id: 27, name: 'Kahve Dünyası', capacity: 78, branch: 'Moda', city: 'İstanbul', country: 'Kadıköy', address: 'Moda Mahallesi, Moda Caddesi Aylin Apartmanı No:188 D:3, 34710 Kadıköy/İstanbul', logo: 'https://logowik.com/content/uploads/images/626_kahvedunyasi.jpg', images: ['https://kahve-pazari.com/wp-content/uploads/2021/03/7-Kahve-Dunyasi-Kadikoy-Medium.jpg', 'https://kadikoytarihicarsi.com/wp-content/uploads/2021/03/kc-kahve-dunyasi1-1024x768.jpg'] },
    { id: 28, name: 'Espressolab', capacity: 250, branch: 'Roastery-Merter', city: 'İstanbul', country: 'Merter', address: 'Tozkoparan Mahallesi General Ali Rıza Gürcan Caddesi Çırpıcı Çıkmazı Sokak No:2 Merter, Güngören/İstanbul', logo: 'https://mir-s3-cdn-cf.behance.net/projects/404/f4feb7135239355.61e94ba480d66.jpg', images: ['https://espressolab.s3.eu-central-1.amazonaws.com/Upload/Sube/Buyuk/1392022-merter-app8-101632.jpg', 'https://espressolab.s3.eu-central-1.amazonaws.com/Upload/Sube/Buyuk/21102022-merter-mimari-app-22-102742.jpg'] },
    { id: 29, name: 'Espressolab', capacity: 92, branch: 'Galataport', city: 'İstanbul', country: 'Beyoğlu', address: 'Kılıçali Paşa, Meclis-i Mebusan Cd. No: 6, 34433 Beyoğlu/İstanbul', logo: 'https://mir-s3-cdn-cf.behance.net/projects/404/f4feb7135239355.61e94ba480d66.jpg', images: ['https://lh3.googleusercontent.com/p/AF1QipP0NiNDFwF1fKNFvgU0GTr_b0RWBd36sr8C5rrq=s680-w680-h510', 'https://lh3.googleusercontent.com/p/AF1QipPyJs7WYT8gNd2TvzEpUJQfw6PDvTBVp4zMs9uW=s680-w680-h510'] },
    { id: 30, name: 'Espressolab', capacity: 72, branch: 'Moda', city: 'İstanbul', country: 'Kadıköy', address: 'Caferağa, Moda Cd. No: 171/A, 34710 Kadıköy/İstanbul', logo: 'https://mir-s3-cdn-cf.behance.net/projects/404/f4feb7135239355.61e94ba480d66.jpg', images: ['https://lh3.googleusercontent.com/p/AF1QipNVQE7F3Li_PY_z_VJIJleu1J71Asw5K8_FTEtl=s680-w680-h510', 'https://lh3.googleusercontent.com/p/AF1QipOt-wYG-byvHisOygGLZLzBcW_eiOBD_YTpF6By=s680-w680-h510'] },
    { id: 31, name: 'Espressolab', capacity: 68, branch: 'Caddebostan', city: 'İstanbul', country: 'Kadıköy', address: 'Caddebostan, Erenköy Mah, Funda Çk Sk. No: 1, 34738 Kadıköy/İstanbul', logo: 'https://mir-s3-cdn-cf.behance.net/projects/404/f4feb7135239355.61e94ba480d66.jpg', images: ['https://lh3.googleusercontent.com/p/AF1QipM0n6m2K0mDURp5AxndjWDIngsLkT1be0Cbl8GY=s680-w680-h510', 'https://lh3.googleusercontent.com/p/AF1QipNVPHp4uNONrbyTQcThJLautXvhn0NaMAfkvbqf=s680-w680-h510'] },
    { id: 32, name: 'Espressolab', capacity: 92, branch: 'Rumeli Hisarı', city: 'İstanbul', country: 'Sarıyer', address: 'Rumeli Hisarı, Yahya Kemal Cd. No: 8, 34450 Sarıyer/İstanbul', logo: 'https://mir-s3-cdn-cf.behance.net/projects/404/f4feb7135239355.61e94ba480d66.jpg', images: ['https://lh3.googleusercontent.com/p/AF1QipMWxnVRxNTpy04YqmvuDvGFYJlDPTwq8SMfR0g5=s680-w680-h510', 'https://lh3.googleusercontent.com/p/AF1QipPwlqZ-c6vTUIlpuX8vMLcqxJMcF5hT-oZ2-4eA=s680-w680-h510'] },
    { id: 33, name: 'Gloria Jeans', capacity: 52, branch: 'AVCILAR', city: 'İstanbul', country: 'Avcılar', address: 'MERKEZ MAH. AHMET TANER KIŞLALI CAD. NO:25/A AVCILAR / İSTANBUL AVCILAR - İSTANBUL', logo: 'https://www.gloriajeans.com.tr/assets/images/config/loader.png', images: ['https://gjcsweb.limonistcustomer.com/GJC1979/mobil_tr/imgs/branch_images/1-20180910-163355.jpg', 'https://lh5.googleusercontent.com/p/AF1QipNxsj3QG4jXhkeCCPzru0jJLJs5CLjUDKljFWHD=w500-h500-k-no'] },
    { id: 34, name: 'Gloria Jeans', capacity: 63, branch: 'Aqua Florya', city: 'İstanbul', country: 'Florya', address: 'Şenlikköy, Aqua Florya, 34153 Bakırköy/İstanbul', logo: 'https://www.gloriajeans.com.tr/assets/images/config/loader.png', images: ['https://lh3.googleusercontent.com/p/AF1QipMk-Zx7055RuLLl2oLqtCmAEwduo58as1OlGaAC=s680-w680-h510', 'https://lh3.googleusercontent.com/p/AF1QipOlV1ZjhrpCTbdJa9OvVyd5ld3PqxYzjEvnjUqb=s680-w680-h510'] },
    { id: 35, name: 'Gloria Jeans', capacity: 71, branch: 'Yeşilköy', city: 'İstanbul', country: 'Bakırköy', address: 'Yeşilköy, Serbesti Cd. NO:8-10, 34140 Bakırköy/İstanbul', logo: 'https://www.gloriajeans.com.tr/assets/images/config/loader.png', images: ['https://lh3.googleusercontent.com/p/AF1QipMgTlkspbVBWFDZG8OgdDDcc0id2JxUxx0y8IVj=s680-w680-h510', 'https://lh3.googleusercontent.com/p/AF1QipN_8CE37AEg1E2kIsHOItQTrdviCREAu5AWkejh=s680-w680-h510'] },
    { id: 36, name: 'Gloria Jeans', capacity: 90, branch: 'Mall of İstanbul', city: 'İstanbul', country: 'Başakşehir', address: 'Ziya Gökalp Mah. Süleyman Demirel Cad. No: 7 Mall Of İstanbul D: 79-280 K: 2, 34480 Başakşehir/İstanbul', logo: 'https://www.gloriajeans.com.tr/assets/images/config/loader.png', images: ['https://lh3.googleusercontent.com/p/AF1QipMnyXl_ves6AyEdbfGAxZok8zkBzIXrw1YrG8T8=s680-w680-h510', 'https://lh3.googleusercontent.com/p/AF1QipMLTiBoC4Q3mqX0HmbzoIivUhUOkEHu1ptJ-15e=s680-w680-h510'] },
    { id: 37, name: 'Gloria Jeans', capacity: 69, branch: 'Beşyol', city: 'İstanbul', country: 'Küçükçekmece', address: 'Beşyol, Birlik Cd. No:2, 34295 Küçükçekmece/İstanbul', logo: 'https://www.gloriajeans.com.tr/assets/images/config/loader.png', images: ['https://lh3.googleusercontent.com/p/AF1QipNroFXdQBnuS9e9tJGGGdVRbrQUY2Eb_w8teRyF=s680-w680-h510', 'https://lh3.googleusercontent.com/p/AF1QipPEpkOrA4Kwy0PnXdzjBoO-CkivrLzTPaZ_aTD0=s680-w680-h510'] },
    { id: 38, name: 'MENDELs Chocolatier', capacity: 62, branch: 'Akaretler', city: 'İstanbul', country: 'Beşiktaş', address: 'Sinanpaşa, Şair Nedim Cd. 18/A, 34357 Beşiktaş/İstanbul', logo: 'https://media.licdn.com/dms/image/D5603AQEfFQj6EqPWEg/profile-displayphoto-shrink_800_800/0/1666364351459?e=2147483647&v=beta&t=YKKXC5pNXImNj35J2Eda7medq2MjuYKVpMBx22-wvUY', images: ['https://media-cdn.tripadvisor.com/media/photo-p/13/de/fd/ea/largejpg.jpg', 'https://biyudum.com/images/vitrin/v24fe35eeb.jpg'] },
    { id: 39, name: 'Viyana Kahvesi', capacity: 65, branch: 'Fişekhane', city: 'İstanbul', country: 'Zeytinburnu', address: 'Kazlıçeşme, No:52T İç Kapı, Kennedy Cad. No: B03, 34020 Zeytinburnu/İstanbul', logo: 'https://upload-isinolsun-com.mncdn.com/Company/Job/2023/12/22/750222520231222015850547.jpg', images: ['https://viyanakahvesi.com/wp-content/uploads/2022/10/BAGDAT-CADDESI-scaled.jpg', 'https://viyanakahvesi.com/wp-content/uploads/2021/07/viyana-kahvesi-kosuyolu.gif'] },
    { id: 40, name: 'Viyana Kahvesi', capacity: 72, branch: 'Beşiktaş', city: 'İstanbul', country: 'Beşiktaş', address: 'Sinanpaşa, Yeni Hamam Sk. No:4, 34353 Beşiktaş/İstanbul', logo: 'https://upload-isinolsun-com.mncdn.com/Company/Job/2023/12/22/750222520231222015850547.jpg', images: ['https://viyanakahvesi.com/wp-content/uploads/2021/07/viyana-kahvesi-besiktas.gif', 'https://biyudum.com/images/slider/s21k9y31lk.jpg'] },
    { id: 41, name: 'Viyana Kahvesi', capacity: 52, branch: 'GALATA', city: 'İstanbul', country: 'Beyoğlu', address: 'Bereketzade, Büyük Hendek Cd. No:19/A, 34421 Beyoğlu/İstanbul', logo: 'https://upload-isinolsun-com.mncdn.com/Company/Job/2023/12/22/750222520231222015850547.jpg', images: ['https://lh3.googleusercontent.com/p/AF1QipNAF4nVYQDfbJ4zSAmcGzILkxYDz1pUGGH-9cho=s680-w680-h510', 'https://lh3.googleusercontent.com/p/AF1QipPGrbm-8exOKCJyFLcnHvtkTbppsoy-uMkD9CuV=s680-w680-h510'] },
    { id: 42, name: 'Viyana Kahvesi', capacity: 91, branch: 'Kadıköy', city: 'İstanbul', country: 'Kadıköy', address: 'Caferağa mah. Neşet Ömer sok Kadıköy İş Merkezi No: 1/B307, 34710 Kadıköy', logo: 'https://upload-isinolsun-com.mncdn.com/Company/Job/2023/12/22/750222520231222015850547.jpg', images: ['https://lh3.googleusercontent.com/p/AF1QipMfaebpykE5ElpLgY3a5-QuXhAaf_2tCkhMELfn=s680-w680-h510', 'https://lh3.googleusercontent.com/p/AF1QipM6z6aUpj7mbvy8KB-AQm46sOzM-JPWwiw6_J_N=s680-w680-h510'] },
    { id: 43, name: 'Viyana Kahvesi', capacity: 78, branch: 'VIALAND AVM', city: 'İstanbul', country: 'Eyüpsultan', address: 'Yeşilpınar, Şht. Metin Kaya Sk. No: 11, 34065 Eyüpsultan/İstanbul', logo: 'https://upload-isinolsun-com.mncdn.com/Company/Job/2023/12/22/750222520231222015850547.jpg', images: ['https://lh3.googleusercontent.com/p/AF1QipNUsFjoOPzVN_yH-96MiTMwgUhRQC5poiGYrtaV=s680-w680-h510', 'https://lh3.googleusercontent.com/p/AF1QipPn1vqs9D8pMtvl87E3hAx0Gmc0_0iQlaX-Q8UP=s680-w680-h510'] },
  ];

  return (
    <div >
      <Routes>
        <Route path='/' element={<Home23 />} />
        <Route path='/23' element={<Home23 />} />
        <Route path='/banks' element={<DashboardBaseLayout><BanksPage list={banks} /></DashboardBaseLayout>} />
        <Route path='/libraries' element={<DashboardBaseLayout><LibrariesPage list={libraries} /></DashboardBaseLayout>} />
        <Route path='/caffes' element={<DashboardBaseLayout><CaffesPage list={caffes} /></DashboardBaseLayout>} />
        <Route path='/place' element={<InBaseLayout><PlacePage /></InBaseLayout>} />
        <Route path='/caffe/:id' element={<InBaseLayout><CaffeDetailPage /></InBaseLayout>} />
        <Route path='/library/:id' element={<InBaseLayout><LibraryDetailPage /></InBaseLayout>} />
        <Route path='/bank/:id' element={<InBaseLayout><BankDetailPage /></InBaseLayout>} />
      </Routes>
    </div>
  );
}

export default App;
